<?
define("HIDE_SIDEBAR", true);
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("Корзина");
?>

<?$APPLICATION->IncludeComponent(
	"bitrix:sale.basket.basket", 
	"bootstrap_v4", 
	array(
        "BASKET_WITH_ORDER_INTEGRATION" => "Y",
		"COUNT_DISCOUNT_4_ALL_QUANTITY" => "N",
		"COLUMNS_LIST" => array(
			0 => "NAME",
			1 => "DISCOUNT",
			2 => "PRICE",
			3 => "QUANTITY",
			4 => "SUM",
			5 => "PROPS",
			6 => "DELETE",
			7 => "DELAY",
		),
		"AJAX_MODE" => "N",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "Y",
		"AJAX_OPTION_HISTORY" => "N",
		"PATH_TO_ORDER" => "/bonus-shop/personal/order/make/",
		"HIDE_COUPON" => "Y",
		"QUANTITY_FLOAT" => "N",
		"PRICE_VAT_SHOW_VALUE" => "Y",
		"TEMPLATE_THEME" => "site",
		"SET_TITLE" => "Y",
		"AJAX_OPTION_ADDITIONAL" => "",
		"OFFERS_PROPS" => array(
			0 => "SIZES_SHOES",
			1 => "SIZES_CLOTHES",
			2 => "COLOR_REF",
		),
		"COMPONENT_TEMPLATE" => "bootstrap_v4",
		"DEFERRED_REFRESH" => "N",
		"USE_DYNAMIC_SCROLL" => "Y",
		"SHOW_FILTER" => "N",
		"SHOW_RESTORE" => "Y",
		"COLUMNS_LIST_EXT" => array(
			0 => "PREVIEW_PICTURE",
			1 => "DISCOUNT",
			2 => "DELETE",
			3 => "DELAY",
			4 => "TYPE",
			5 => "SUM",
		),
		"COLUMNS_LIST_MOBILE" => array(
			0 => "PREVIEW_PICTURE",
			1 => "DISCOUNT",
			2 => "DELETE",
			3 => "DELAY",
			4 => "TYPE",
			5 => "SUM",
		),
		"TOTAL_BLOCK_DISPLAY" => array(
			0 => "top",
		),
		"DISPLAY_MODE" => "compact",
		"PRICE_DISPLAY_MODE" => "Y",
		"SHOW_DISCOUNT_PERCENT" => "Y",
		"DISCOUNT_PERCENT_POSITION" => "bottom-right",
		"PRODUCT_BLOCKS_ORDER" => "props,sku,columns",
		"USE_PRICE_ANIMATION" => "Y",
		"LABEL_PROP" => array(
		),
		"USE_PREPAYMENT" => "N",
		"CORRECT_RATIO" => "Y",
		"AUTO_CALCULATION" => "Y",
		"ACTION_VARIABLE" => "basketAction",
		"COMPATIBLE_MODE" => "Y",
		"EMPTY_BASKET_HINT_PATH" => "/",
		"ADDITIONAL_PICT_PROP_17" => "-",
		"ADDITIONAL_PICT_PROP_18" => "-",
		"BASKET_IMAGES_SCALING" => "adaptive",
		"USE_GIFTS" => "N",
		"GIFTS_PLACE" => "BOTTOM",
		"GIFTS_BLOCK_TITLE" => "Выберите один из подарков",
		"GIFTS_HIDE_BLOCK_TITLE" => "N",
		"GIFTS_TEXT_LABEL_GIFT" => "Подарок",
		"GIFTS_PRODUCT_QUANTITY_VARIABLE" => "quantity",
		"GIFTS_PRODUCT_PROPS_VARIABLE" => "prop",
		"GIFTS_SHOW_OLD_PRICE" => "N",
		"GIFTS_SHOW_DISCOUNT_PERCENT" => "Y",
		"GIFTS_MESS_BTN_BUY" => "Выбрать",
		"GIFTS_MESS_BTN_DETAIL" => "Подробнее",
		"GIFTS_PAGE_ELEMENT_COUNT" => "4",
		"GIFTS_CONVERT_CURRENCY" => "N",
		"GIFTS_HIDE_NOT_AVAILABLE" => "N",
		"USE_ENHANCED_ECOMMERCE" => "N",
		"ADDITIONAL_PICT_PROP_14" => "-",
		"ADDITIONAL_PICT_PROP_15" => "-"
	),
	false
);?>
<?$APPLICATION->IncludeComponent(
    "bitrix:sale.order.ajax",
    "bootstrap_v4",
    array(
        "PAY_FROM_ACCOUNT" => "Y",
        "COUNT_DELIVERY_TAX" => "N",
        "COUNT_DISCOUNT_4_ALL_QUANTITY" => "N",
        "ONLY_FULL_PAY_FROM_ACCOUNT" => "N",
        "ALLOW_AUTO_REGISTER" => "N",
        "SEND_NEW_USER_NOTIFY" => "N",
        "DELIVERY_NO_AJAX" => "N",
        "TEMPLATE_LOCATION" => "popup",
        "PROP_1" => "",
        "PATH_TO_BASKET" => "/bonus-shop/personal/cart/",
        "PATH_TO_PERSONAL" => "/bonus-shop/personal/order/",
        "PATH_TO_PAYMENT" => "/bonus-shop/personal/order/payment/",
        "PATH_TO_ORDER" => "/bonus-shop/personal/order/make/",
        "SET_TITLE" => "Y",
        "SHOW_ACCOUNT_NUMBER" => "Y",
        "DELIVERY_NO_SESSION" => "Y",
        "COMPATIBLE_MODE" => "N",
        "BASKET_POSITION" => "before",
        "BASKET_IMAGES_SCALING" => "adaptive",
        "SERVICES_IMAGES_SCALING" => "adaptive",
        "USER_CONSENT" => "Y",
        "USER_CONSENT_ID" => "2",
        "USER_CONSENT_IS_CHECKED" => "Y",
        "USER_CONSENT_IS_LOADED" => "Y",
        "COMPONENT_TEMPLATE" => "bootstrap_v4",
        "ALLOW_APPEND_ORDER" => "Y",
        "SHOW_NOT_CALCULATED_DELIVERIES" => "N",
        "SPOT_LOCATION_BY_GEOIP" => "N",
        "DELIVERY_TO_PAYSYSTEM" => "d2p",
        "SHOW_VAT_PRICE" => "N",
        "USE_PREPAYMENT" => "N",
        "USE_PRELOAD" => "Y",
        "ALLOW_USER_PROFILES" => "N",
        "ALLOW_NEW_PROFILE" => "N",
        "TEMPLATE_THEME" => "red",
        "SHOW_ORDER_BUTTON" => "always",
        "SHOW_TOTAL_ORDER_BUTTON" => "Y",
        "SHOW_PAY_SYSTEM_LIST_NAMES" => "N",
        "SHOW_PAY_SYSTEM_INFO_NAME" => "N",
        "SHOW_DELIVERY_LIST_NAMES" => "N",
        "SHOW_DELIVERY_INFO_NAME" => "N",
        "SHOW_DELIVERY_PARENT_NAMES" => "N",
        "SHOW_STORES_IMAGES" => "N",
        "SKIP_USELESS_BLOCK" => "N",
        "SHOW_BASKET_HEADERS" => "N",
        "DELIVERY_FADE_EXTRA_SERVICES" => "N",
        "SHOW_NEAREST_PICKUP" => "N",
        "DELIVERIES_PER_PAGE" => "1",
        "PAY_SYSTEMS_PER_PAGE" => "1",
        "PICKUPS_PER_PAGE" => "1",
        "SHOW_PICKUP_MAP" => "N",
        "SHOW_MAP_IN_PROPS" => "N",
        "PICKUP_MAP_TYPE" => "yandex",
        "SHOW_COUPONS" => "Y",
        "SHOW_COUPONS_BASKET" => "Y",
        "SHOW_COUPONS_DELIVERY" => "Y",
        "SHOW_COUPONS_PAY_SYSTEM" => "Y",
        "PROPS_FADE_LIST_3" => array(
        ),
        "PROPS_FADE_LIST_5" => array(
        ),
        "PROPS_FADE_LIST_4" => array(
        ),
        "PROPS_FADE_LIST_6" => array(
        ),
        "ACTION_VARIABLE" => "soa-action",
        "PATH_TO_AUTH" => "/auth/",
        "DISABLE_BASKET_REDIRECT" => "N",
        "EMPTY_BASKET_HINT_PATH" => "/",
        "USE_PHONE_NORMALIZATION" => "Y",
        "PRODUCT_COLUMNS_VISIBLE" => array(
            0 => "PREVIEW_PICTURE",
            1 => "PROPS",
        ),
        "ADDITIONAL_PICT_PROP_17" => "-",
        "ADDITIONAL_PICT_PROP_18" => "-",
        "PRODUCT_COLUMNS_HIDDEN" => array(
        ),
        "HIDE_ORDER_DESCRIPTION" => "N",
        "USE_YM_GOALS" => "N",
        "USE_ENHANCED_ECOMMERCE" => "N",
        "USE_CUSTOM_MAIN_MESSAGES" => "N",
        "USE_CUSTOM_ADDITIONAL_MESSAGES" => "N",
        "USE_CUSTOM_ERROR_MESSAGES" => "N"
    ),
    false
);?>

<?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>